### ISSUE TITLE
Library is broken when upgrading underlying dependencies

### ISSUE THREAD

**Issue by marwan-at-work** [lightstep/otel-launcher-go#109]
**Describe the bug**
When trying to use this library, if the underlying `otlpmetric` is newer than what it is expected, I get the following error:

```
$ go build ./...
# go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetricgrpc
../../go/pkg/mod/go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetricgrpc@v0.26.0/client.go:60:27: cannot use (*client)(nil) (value of type *client) as type otlpmetric.Client in variable declaration:
        *client does not implement otlpmetric.Client (wrong type for UploadMetrics method)
                have UploadMetrics(ctx context.Context, protoMetrics []*"go.opentelemetry.io/proto/otlp/metrics/v1".ResourceMetrics) error
                want UploadMetrics(ctx context.Context, protoMetrics *"go.opentelemetry.io/proto/otlp/metrics/v1".ResourceMetrics) error
../../go/pkg/mod/go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetricgrpc@v0.26.0/client.go:64:9: cannot use newClient(opts...) (value of type *client) as type otlpmetric.Client in return statement:
        *client does not implement otlpmetric.Client (wrong type for UploadMetrics method)
                have UploadMetrics(ctx context.Context, protoMetrics []*"go.opentelemetry.io/proto/otlp/metrics/v1".ResourceMetrics) error
                want UploadMetrics(ctx context.Context, protoMetrics *"go.opentelemetry.io/proto/otlp/metrics/v1".ResourceMetrics) error
../../go/pkg/mod/go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetricgrpc@v0.26.0/options.go:37:43: cannot use o.applyGRPCOption (value of type func(*otlpconfig.Config)) as type func(cfg otlpconfig.Config) otlpconfig.Config in argument to otlpconfig.NewGRPCOption
../../go/pkg/mod/go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetricgrpc@v0.26.0/options.go:54:20: cannot use cfg (variable of type *otlpconfig.Config) as type otlpconfig.Config in argument to w.ApplyGRPCOption
../../go/pkg/mod/go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetricgrpc@v0.26.0/options.go:80:48: cannot use func(cfg *otlpconfig.Config) {…} (value of type func(cfg *otlpconfig.Config)) as type func(cfg otlpconfig.Config) otlpconfig.Config in argument to otlpconfig.NewGRPCOption
../../go/pkg/mod/go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetricgrpc@v0.26.0/options.go:120:48: cannot use func(cfg *otlpconfig.Config) {…} (value of type func(cfg *otlpconfig.Config)) as type func(cfg otlpconfig.Config) otlpconfig.Config in argument to otlpconfig.NewGRPCOption
../../go/pkg/mod/go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetricgrpc@v0.26.0/options.go:129:48: cannot use func(cfg *otlpconfig.Config) {…} (value of type func(cfg *otlpconfig.Config)) as type func(cfg otlpconfig.Config) otlpconfig.Config in argument to otlpconfig.NewGRPCOption
../../go/pkg/mod/go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetricgrpc@v0.26.0/options.go:141:48: cannot use func(cfg *otlpconfig.Config) {…} (value of type func(cfg *otlpconfig.Config)) as type func(cfg otlpconfig.Config) otlpconfig.Config in argument to otlpconfig.NewGRPCOption
../../go/pkg/mod/go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetricgrpc@v0.26.0/options.go:155:48: cannot use func(cfg *otlpconfig.Config) {…} (value of type func(cfg *otlpconfig.Config)) as type func(cfg otlpconfig.Config) otlpconfig.Config in argument to otlpconfig.NewGRPCOption
```
**To Reproduce**
Clone this repo, upgrade the `otlpmetric` module, and run go build.

**Expected behavior**
It doesn't fail.

**Comment by codeboten** [comment]
Hi @marwan-at-work, I just [bumped the dependencies](https://github.com/lightstep/otel-launcher-go/pull/114) for metrics to the latest release 0.27.0. Can you try building with this change to see if it resolves the issue you're seeing here?

**Comment by codeboten** [comment]
What version of `otlpmetric` are you updating to? The following with the latest released version worked locally:

```
root@f1c845d4c38b:/go# git clone https://github.com/lightstep/otel-launcher-go.git
Cloning into 'otel-launcher-go'...
remote: Enumerating objects: 845, done.
remote: Counting objects: 100% (564/564), done.
remote: Compressing objects: 100% (343/343), done.
remote: Total 845 (delta 382), reused 322 (delta 210), pack-reused 281
Receiving objects: 100% (845/845), 421.87 KiB | 1.76 MiB/s, done.
Resolving deltas: 100% (480/480), done.
root@f1c845d4c38b:/go# cd otel-launcher-go/
root@f1c845d4c38b:/go/otel-launcher-go# go build ./...
go: downloading go.opentelemetry.io/otel v1.4.1
go: downloading go.opentelemetry.io/otel/metric v0.27.0
go: downloading go.opentelemetry.io/otel/trace v1.4.1
go: downloading github.com/sethvargo/go-envconfig v0.5.0
go: downloading go.opentelemetry.io/otel/sdk v1.4.1
go: downloading github.com/go-logr/logr v1.2.2
go: downloading go.opentelemetry.io/otel/internal/metric v0.27.0
go: downloading go.opentelemetry.io/contrib/instrumentation/host v0.29.0
go: downloading go.opentelemetry.io/contrib/instrumentation/runtime v0.29.0
go: downloading go.opentelemetry.io/contrib/propagators/b3 v1.4.0
go: downloading go.opentelemetry.io/contrib/propagators/ot v1.4.0
go: downloading go.opentelemetry.io/otel/exporters/otlp/otlpmetric v0.27.0
go: downloading go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetricgrpc v0.27.0
go: downloading go.opentelemetry.io/otel/exporters/otlp/otlptrace v1.4.1
go: downloading go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc v1.4.1
go: downloading go.opentelemetry.io/otel/sdk/metric v0.27.0
go: downloading google.golang.org/grpc v1.45.0
go: downloading github.com/go-logr/stdr v1.2.2
go: downloading github.com/shirou/gopsutil/v3 v3.22.1
go: downloading golang.org/x/sys v0.0.0-20220111092808-5a964db01320
go: downloading go.opentelemetry.io/otel/exporters/otlp/internal/retry v1.4.1
go: downloading go.opentelemetry.io/proto/otlp v0.12.0
go: downloading google.golang.org/genproto v0.0.0-20220112215332-a9c7c0acf9f2
go: downloading github.com/tklauser/go-sysconf v0.3.9
go: downloading github.com/cenkalti/backoff/v4 v4.1.2
go: downloading github.com/golang/protobuf v1.5.2
go: downloading google.golang.org/protobuf v1.27.1
go: downloading github.com/grpc-ecosystem/grpc-gateway v1.16.0
go: downloading golang.org/x/net v0.0.0-20220111093109-d55c255bac03
go: downloading github.com/tklauser/numcpus v0.3.0
go: downloading golang.org/x/text v0.3.7
```

**Comment by marwan-at-work** [comment]
```
$ go get github.com/lightstep/otel-launcher-go@main                       
go: added github.com/lightstep/otel-launcher-go v1.0.1-0.20220316153009-781f01f7dd3e
$ go list -m go.opentelemetry.io/otel/exporters/otlp/otlpmetric
go.opentelemetry.io/otel/exporters/otlp/otlpmetric v0.23.0
```

I believe this is because `otlpmetric` is part of the sub-module which is getting replaced in `otel-launcher-go` but obviously replace statements are not honored when importing `otel-launched-go` as a dependency. So I have to also `go get github.com/lightstep/otel-launcher-go/pipelines@main` explicitly though i don't depend on it directly. 

I think this should be solved once y'all tag a new version for the sub-module and make sure the main module imports it at that version as well.

**Comment by codeboten** [comment]
Published a new tag. Please confirmed if it resolved the issue for you.

**Comment by drewthor** [comment]
@codeboten I highly appreciate the tagged release!

Unfortunately this did not resolve the issue at least for my case.

Still getting:
```
github.com/lightstep/otel-launcher-go/launcher imports
	github.com/lightstep/otel-launcher-go/pipelines imports
	go.opentelemetry.io/otel/sdk/metric/controller/basic imports
	go.opentelemetry.io/otel/metric/registry: module go.opentelemetry.io/otel/metric@latest found (v0.27.0), but does not contain package go.opentelemetry.io/otel/metric/registry
```

In order to resolve this I have to manually go in and and upgrade some of the indirect dependencies to their latest versions

**Comment by drewthor** [comment]
@codeboten it appears that the tagged `otel-launcher-go` module is requiring the older `pipelines` `v0.0.0-20220106234948-aab622036bba` which is not compatible due to it using otel/metric v0.23.0 (where metric/registry has since moved in later versions to internal). It is also not a tagged release version for some reason. `otel-launcher-go` would need to be targeting the latest tagged release of `pipelines` which is `v0.0.0-20220318151737-bad054fb476e`

**Comment by codeboten** [comment]
Thanks @drewthor, I've tagged the pipelines package and released `v1.5.1` with an updated dependency.
